import { useEffect,useMemo,useState } from 'react';
import type { Session,SupabaseClient } from '@supabase/supabase-js';
import { Dumbbell,Mail,Lock,ArrowUpRight } from 'lucide-react';
import { connect,demoRepository,supabaseRepository } from './backend';
import { demoEntries } from './demo';
import Tracker from './Tracker';
export default function App(){
 const [client,setClient]=useState<SupabaseClient|null>(null),[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[demo,setDemo]=useState(()=>new URLSearchParams(window.location.search).has('demo')),[error,setError]=useState(''),[recovery,setRecovery]=useState(false);
 useEffect(()=>{let active=true,unsubscribe=()=>{};connect().then(async c=>{if(!active)return;setClient(c);if(c){const {data,error}=await c.auth.getSession();if(!active)return;if(error)setError('Oturum yüklenemedi. Yeniden giriş yap.');setSession(data.session);const {data:sub}=c.auth.onAuthStateChange((event,s)=>{setSession(s);if(event==='PASSWORD_RECOVERY')setRecovery(true)});unsubscribe=()=>sub.subscription.unsubscribe();}setLoading(false)}).catch(e=>{if(active){setError(e.message);setLoading(false)}});return()=>{active=false;unsubscribe()};},[]);
 const repo=useMemo(()=>demo?demoRepository(demoEntries()):client&&session?supabaseRepository(client,session.user.id):null,[demo,client,session?.user.id]);
 if(loading)return <div className="auth-page"><Brand/><p className="muted">Defterin açılıyor…</p></div>;
 if(repo&&!recovery)return <Tracker key={demo?'demo':session!.user.id} repo={repo} userId={demo?'demo':session!.user.id} demo={demo} onLogout={async()=>{if(demo)setDemo(false);else {const r=await client!.auth.signOut();if(r.error)throw r.error;}}}/>;
 return <div className="auth-page"><Brand/><div className="auth-card"><p className="eyebrow">KENDİ TEMPO'NDA</p><h1>Her setin bir kaydı olsun.</h1><p className="auth-intro">Bugünkü antrenmanını kaydet. Bir sonraki sefer nereden başlayacağını bil.</p>{error&&<p className="error" role="alert">{error}</p>}{client?<Auth client={client} recovery={recovery} recovered={()=>setRecovery(false)}/>:<div className="note"><strong>Hesap bağlantısı hazırlanıyor.</strong><p>Supabase bağlandığında antrenmanların telefon ve bilgisayarında aynı hesapta saklanacak.</p></div>}<button className="secondary demo-button" onClick={()=>setDemo(true)}>Örnek verilerle uygulamayı dene <ArrowUpRight size={17}/></button><p className="muted">Demo kayıtları örnektir; sayfa kapatılınca silinir.</p></div><p className="auth-footer">Set Defterim · Kişisel alanın</p></div>;
}
function Brand(){return <header className="brand"><span className="brand-icon"><Dumbbell/></span><div><strong>SET DEFTERİM</strong><small>Kişisel antrenman günlüğün</small></div></header>}
function Auth({client,recovery,recovered}:{client:SupabaseClient;recovery:boolean;recovered:()=>void}){
 const [mode,setMode]=useState<'login'|'signup'|'reset'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const redirect=new URL(import.meta.env.BASE_URL,window.location.href).href;let result;if(recovery){result=await client.auth.updateUser({password});if(!result.error)recovered();}else if(mode==='login')result=await client.auth.signInWithPassword({email,password});else if(mode==='signup'){result=await client.auth.signUp({email,password,options:{emailRedirectTo:redirect}});if(!result.error)setMessage('E-postanı kontrol et. Hesabını doğruladıktan sonra giriş yapabilirsin.');}else{result=await client.auth.resetPasswordForEmail(email,{redirectTo:redirect});if(!result.error)setMessage('Hesabın varsa şifre yenileme bağlantısı e-postana gönderildi.');}if(result.error){const msg=result.error.message;throw new Error(msg.includes('Invalid login')?'E-posta veya şifre hatalı.':msg.includes('confirmed')?'Önce e-posta adresini doğrula.':msg.includes('rate limit')?'Çok fazla deneme yapıldı. Biraz sonra tekrar dene.':'İşlem tamamlanamadı. Bilgilerini ve bağlantını kontrol et.');}}catch(e){setError(e instanceof Error?e.message:'İşlem tamamlanamadı.')}finally{setBusy(false)}}
 return <form onSubmit={submit} className="auth-form"><h2>{recovery?'Yeni şifre':mode==='login'?'Hesabına giriş yap':mode==='signup'?'Hesap oluştur':'Şifreni yenile'}</h2>{!recovery&&<label><span><Mail size={15}/> E-posta</span><input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>}{(recovery||mode!=='reset')&&<label><span><Lock size={15}/> Şifre</span><input type="password" autoComplete={mode==='signup'||recovery?'new-password':'current-password'} minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label>}{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="note" role="status">{message}</p>}<button disabled={busy} className="primary">{busy?'Bekle…':recovery?'Şifreyi güncelle':mode==='login'?'Giriş yap':mode==='signup'?'Hesap oluştur':'Yenileme bağlantısı gönder'}</button>{!recovery&&<div className="auth-links"><button type="button" className="ghost" onClick={()=>{setMode(mode==='signup'?'login':'signup');setError('');setMessage('')}}>{mode==='signup'?'Zaten hesabım var':'Hesap oluştur'}</button><button type="button" className="ghost" onClick={()=>{setMode(mode==='reset'?'login':'reset');setError('');setMessage('')}}>{mode==='reset'?'Girişe dön':'Şifremi unuttum'}</button></div>}</form>;
}
